language: node_js
node_js: 
  - "10.15.3"
script:
  - npm install
  - CI=false npm run build
  - cd functions && npm install
  - cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  project: 1:504717594119:web:5534754aacb79e3f6724a2